/** Exact legacy names only: later staff corrections remain authoritative. */
const RECOGNIZABLE_NAMES: Record<string, string> = {
  "Glúteo / extensión de cadera": "Patada de glúteo",
  "Hip Abductor": "Abductores de cadera",
  "Hip Abduction": "Abductores de cadera",
  "Abductor / Aductor (dual)": "Abductores y aductores",
  "Prensa inclinada": "Prensa de piernas inclinada",
  "Prensa horizontal": "Prensa de piernas horizontal",
  "Sentadilla acostado": "Sentadilla acostada",
  "Leg Extension": "Extensión de piernas",
  "Leg Curl sentado": "Curl femoral sentado",
  "Leg Curl + Leg Extension (dual)": "Curl y extensión de piernas",
  "Leg Curl acostado (camilla)": "Curl femoral acostado",
  "Máquina Smith libre": "Máquina Smith",
  "Sissy Squats": "Sentadilla sissy",
  "Hack Squat": "Sentadilla hack",
  "Sentadilla Perfecta": "Sentadilla perfecta",
  "Máquina pequeña, tubo con pesas en extremos": "Tubo con pesas (por identificar)",
  "Máquina de pie tipo multi-estación": "Multiestación de pie",
  "Hip Thrust (rack con plataforma)": "Empuje de cadera (hip thrust)",
  "Caminadora tipo escalera/pasos (stepper)": "Escaladora de pedales",
  "Máquina de gradas (stair climber)": "Escalera de gradas",
  "Remo cerrado (Hammer Strength)": "Remo cerrado (Hammer)",
  "Dominada asistida": "Dominadas asistidas",
  "Dominada asistida (segunda unidad)": "Dominadas asistidas",
  "Jalón (polea)": "Jalón al pecho",
  "Remo T": "Remo en T",
  "Prensa de hombros (asiento, peso atrás, empuje hacia arriba y al frente)": "Press de hombros",
  "Bicicleta": "Bicicleta estática",
  "Máquina multi-estación (asiento ajustable, soporte de espalda, plataforma frontal, agarraderas múltiples)": "Multiestación con asiento",
  "Máquina de gradas (stepper) - unidad 1": "Escaladora de pedales",
  "Máquina de gradas (stepper) - unidad 2": "Escaladora de pedales",
  "Press plano": "Press de pecho plano",
  "Aperturas posteriores / Pec Deck Rear Delt (Fly Rear Delt)": "Aperturas de hombro posterior",
  "Overhead press (press militar)": "Press militar",
  "Abdominal": "Abdominales en máquina",
  "Back extension": "Extensión lumbar",
  "Press inclinado": "Press de pecho inclinado",
  "Aperturas de pecho (Titanium) - brazos hacia el frente": "Mariposa de pecho (Titanium)",
  "Chest Incline Press (más nueva, similar a la Titanium)": "Press de pecho inclinado",
  "Banca inclinada con postes en ángulo hacia arriba, pesos a los lados": "Banca inclinada con postes",
  "Predicador (Pressure Curve), asistido": "Curl de bíceps (Pressure Curve)",
  "Predicador (marca amarilla)": "Curl de bíceps (amarilla)",
  "Extensión de codo": "Extensión de tríceps",
  "Fondos (dips)": "Fondos en máquina",
  "Polea crossover, 4 estaciones (banquita, apoyo de rodillas, poleas abajo, polea arriba)": "Polea de 4 estaciones",
  "Polea (cable)": "Polea ajustable",
  "Polea roja - unidad 1": "Polea roja",
  "Polea roja - unidad 2": "Polea roja",
};

export function migrateMachineName(name: string): string {
  if (/^Cinta de correr \(caminadora\)(?: - otro lado)? #\d+$/.test(name)) return "Caminadora";
  return RECOGNIZABLE_NAMES[name] ?? name;
}
