import {
  Activity,
  Baby,
  CalendarCheck,
  Dumbbell,
  GlassWater,
  Ruler,
  Smartphone,
  Sparkles,
  Sun,
  Users,
} from "lucide-react";

const sharedMedia = {
  machinesVideo: "/xtreme/scene-machines-pexels.mp4",
  machinesCredit: "Navdeep Singh / Pexels",
  machinesCreditHref: "https://www.pexels.com/video/person-working-out-in-the-gym-14183169/",
  strengthVideo: "/xtreme/hero-training-pexels.mp4",
  strengthCredit: "utopia 36 / Pexels",
  strengthCreditHref: "https://www.pexels.com/video/training-at-gym-12188781/",
} as const;

export const HOME_CONTENT = {
  es: {
    systemStatus: "Sistema Xtreme · activo",
    eyebrow: "Entrenamiento · Ciudad Quesada",
    heroLine1: "Entrena.",
    heroLine2: "En serio.",
    heroText: "Espacio, equipo y dirección para convertir una decisión en constancia. Tu primer día va por nuestra cuenta.",
    primaryCta: "Empezá gratis",
    primaryHref: "/primer-dia",
    secondaryCta: "Ver planes",
    secondaryHref: "/precios#inscripcion",
    discover: "Descubrí más",
    ideaEyebrow: "La idea es simple",
    ideaTitle: "Un buen gym no te grita.",
    ideaHighlight: "Te da razones para volver.",
    ideaText: "Menos fricción. Más claridad. Un lugar que acompaña la decisión que ya tomaste.",
    marquee: ["Fuerza", "Constancia", "Movimiento", "Dirección", "Progreso", "Xtreme Gym"],
    servicesEyebrow: "Más que máquinas",
    servicesTitle: "Todo alrededor de tu progreso.",
    servicesText: "Entrenamiento, medición, recuperación y espacios pensados para que venir al gym sea más fácil y más completo.",
    pathsEyebrow: "Tu entrada",
    pathsTitle: "Elegí por dónde empezar.",
    pathsText: "Cuatro caminos claros. Sin una pared de tarjetas compitiendo por tu atención.",
    danceEyebrow: "También en Xtreme",
    danceTeacher: "Profesora Natalia Zapata",
    danceTitle: "Valari",
    danceHighlight: "Dance Studio.",
    danceText: "Clases de salsa, bachata y baile popular para diferentes niveles. También creamos coreografías para bodas, quince años, celebraciones de 50 años y Festivales de las Artes.",
    danceCta: "WhatsApp 6179-2121",
    finalCta: "La decisión puede empezar hoy. El primer día corre por nuestra cuenta.",
    finalCtaLabel: "Ver planes y pagar",
    scenes: [
      {
        number: "01", eyebrow: "Un piso que responde", title: "Todo para entrenar. Nada para distraerte.",
        text: "Peso libre, fuerza guiada, cardio y zonas funcionales conviven en un espacio amplio. Llegás con un objetivo y encontrás el equipo para trabajarlo.",
        image: "/xtreme/piso-maquinas-panoramica.webp", video: sharedMedia.machinesVideo,
        videoCredit: sharedMedia.machinesCredit, videoHref: sharedMedia.machinesCreditHref,
        alt: "Piso panorámico de máquinas de Xtreme Gym", href: "/zonas", cta: "Recorrer las zonas",
        icon: Dumbbell, facts: ["5 zonas", "Equipo completo", "Desde las 5 AM"],
      },
      {
        number: "02", eyebrow: "Member OS", title: "Tu constancia también vive fuera del gym.",
        text: "Reservas, plan, rachas, progreso y carné digital en una experiencia diseñada para decirte qué sigue.",
        image: "/xtreme/maquinas-y-entrenador-xtreme.webp", video: null, videoCredit: null, videoHref: null,
        alt: "Socio entrenando con acompañamiento en Xtreme Gym", href: "/app", cta: "Abrir la app",
        icon: Smartphone, facts: ["Reservas reales", "Progreso visible", "Acceso privado"],
      },
      {
        number: "03", eyebrow: "Dirección humana", title: "Tecnología cuando ayuda. Personas cuando importa.",
        text: "El equipo te orienta, la medición corporal pone contexto y la comunidad hace más fácil volver.",
        image: "/xtreme/zona-funcional-clases.webp", video: sharedMedia.strengthVideo,
        videoCredit: sharedMedia.strengthCredit, videoHref: sharedMedia.strengthCreditHref,
        alt: "Entrenamiento guiado en la zona funcional de Xtreme Gym", href: "/beneficios", cta: "Ver lo que incluye",
        icon: Activity, facts: ["Medición incluida", "Guía de instructores", "Comunidad Xtreme"],
      },
    ],
    paths: [
      { number: "01", title: "Probá el gym", text: "Tu primer día es gratis.", href: "/primer-dia", icon: Sparkles },
      { number: "02", title: "Elegí tu plan", text: "Semana, quincena o mes.", href: "/precios", icon: CalendarCheck },
      { number: "03", title: "Conocé las zonas", text: "Encontrá dónde avanzar.", href: "/zonas", icon: Dumbbell },
      { number: "04", title: "Entrá a Member OS", text: "Tu progreso en un lugar.", href: "/app", icon: Smartphone },
    ],
    services: [
      { number: "01", title: "Entrenamiento en sala", text: "Medición, rutina y acompañamiento de un instructor o instructora de planta.", meta: "Medición · rutina · acompañamiento", image: "/xtreme/maquinas-y-entrenador-xtreme.webp", icon: Dumbbell },
      { number: "02", title: "Semi­personalizado", text: "Entrenamiento en grupos de máximo seis integrantes con un profesional a cargo.", meta: "Grupos de hasta 6 personas", image: "/xtreme/zona-funcional-clases.webp", icon: Users },
      { number: "03", title: "Zona VIP", text: "Área exclusiva dirigida por el coach Alberto Castro Porras.", meta: "Contacto · 8387-6209", image: "/xtreme/zona-entrenamiento-vip.webp", href: "https://wa.me/50683876209", icon: Sparkles },
      { number: "04", title: "InBody", text: "Mediciones antropométricas para orientar mejor tu plan de entrenamiento.", meta: "Datos para entrenar con dirección", image: "/xtreme/consultorio-medicion-corporal.webp", icon: Ruler },
      { number: "05", title: "Sala de bronceado", text: "Un espacio dedicado para conseguir y mantener el tono de piel que buscás.", meta: "Bienestar · imagen personal", image: "/xtreme/recepcion-sala-espera.webp", icon: Sun },
      { number: "06", title: "Batidos proteicos", text: "Opciones prácticas para complementar o reponer energía.", meta: "Recuperación · energía", image: "/xtreme/piso-pesas-panoramica.webp", icon: GlassWater },
      { number: "07", title: "Sala para peques", text: "Área de juego para tener a los peques cerca mientras entrenás.", meta: "Espacio infantil sin servicio de cuido", image: "/xtreme/area-infantil.webp", icon: Baby },
      { number: "08", title: "Adulto mayor", text: "Clases grupales dirigidas por el coach Fabio Porras Molina.", meta: "Movimiento · fuerza · comunidad", image: "/xtreme/zona-funcional-amplia.webp", href: "/adultos-mayores", icon: Activity },
    ],
  },
  en: {
    systemStatus: "Xtreme system · active",
    eyebrow: "Training · Ciudad Quesada",
    heroLine1: "Train.",
    heroLine2: "For real.",
    heroText: "The space, equipment and guidance to turn one decision into consistency. Your first day is on us.",
    primaryCta: "Start for free",
    primaryHref: "/en/first-day",
    secondaryCta: "View plans",
    secondaryHref: "/en/prices#inscripcion",
    discover: "Discover more",
    ideaEyebrow: "The idea is simple",
    ideaTitle: "A good gym does not shout.",
    ideaHighlight: "It gives you reasons to return.",
    ideaText: "Less friction. More clarity. A place that supports the decision you already made.",
    marquee: ["Strength", "Consistency", "Movement", "Guidance", "Progress", "Xtreme Gym"],
    servicesEyebrow: "More than machines",
    servicesTitle: "Everything around your progress.",
    servicesText: "Training, assessment, recovery and practical spaces designed to make every gym visit easier and more complete.",
    pathsEyebrow: "Your entry point",
    pathsTitle: "Choose where to begin.",
    pathsText: "Four clear paths, without a wall of cards fighting for your attention.",
    danceEyebrow: "Also at Xtreme",
    danceTeacher: "Instructor Natalia Zapata",
    danceTitle: "Valari",
    danceHighlight: "Dance Studio.",
    danceText: "Salsa, bachata and popular dance classes for different levels. Choreography services are also available for weddings, quinceañeras, 50th celebrations and Festival of the Arts performances.",
    danceCta: "WhatsApp 6179-2121",
    finalCta: "Your decision can start today. Your first day is on us.",
    finalCtaLabel: "View plans and join",
    scenes: [
      {
        number: "01", eyebrow: "A floor that delivers", title: "Everything to train. Nothing to distract you.",
        text: "Free weights, guided strength, cardio and functional areas come together in one complete training space.",
        image: "/xtreme/piso-maquinas-panoramica.webp", video: sharedMedia.machinesVideo,
        videoCredit: sharedMedia.machinesCredit, videoHref: sharedMedia.machinesCreditHref,
        alt: "Panoramic view of the Xtreme Gym machine floor", href: "/en/training", cta: "Explore training areas",
        icon: Dumbbell, facts: ["5 areas", "Complete equipment", "Open from 5 AM"],
      },
      {
        number: "02", eyebrow: "Member OS", title: "Your consistency continues outside the gym.",
        text: "Bookings, memberships, streaks, progress and your digital card in one focused member experience.",
        image: "/xtreme/maquinas-y-entrenador-xtreme.webp", video: null, videoCredit: null, videoHref: null,
        alt: "Member training with guidance at Xtreme Gym", href: "/app", cta: "Open the member app",
        icon: Smartphone, facts: ["Live bookings", "Visible progress", "Private access"],
      },
      {
        number: "03", eyebrow: "Human guidance", title: "Technology when it helps. People when it matters.",
        text: "Our team guides you, body assessments add context and the community makes returning easier.",
        image: "/xtreme/zona-funcional-clases.webp", video: sharedMedia.strengthVideo,
        videoCredit: sharedMedia.strengthCredit, videoHref: sharedMedia.strengthCreditHref,
        alt: "Guided workout in the Xtreme Gym functional area", href: "/en/benefits", cta: "See what is included",
        icon: Activity, facts: ["Body assessment", "Instructor guidance", "Xtreme community"],
      },
    ],
    paths: [
      { number: "01", title: "Try the gym", text: "Your first day is free.", href: "/en/first-day", icon: Sparkles },
      { number: "02", title: "Choose a plan", text: "Week, fortnight or month.", href: "/en/prices", icon: CalendarCheck },
      { number: "03", title: "Explore the areas", text: "Find where to move forward.", href: "/en/training", icon: Dumbbell },
      { number: "04", title: "Enter Member OS", text: "Your progress in one place.", href: "/app", icon: Smartphone },
    ],
    services: [
      { number: "01", title: "Gym-floor training", text: "Body assessment, training routine and support from an on-floor instructor.", meta: "Assessment · routine · support", image: "/xtreme/maquinas-y-entrenador-xtreme.webp", icon: Dumbbell },
      { number: "02", title: "Semi-personal training", text: "Training groups of no more than six members with a dedicated coach.", meta: "Groups of up to 6", image: "/xtreme/zona-funcional-clases.webp", icon: Users },
      { number: "03", title: "VIP area", text: "An exclusive area led by coach Alberto Castro Porras.", meta: "Contact · 8387-6209", image: "/xtreme/zona-entrenamiento-vip.webp", href: "https://wa.me/50683876209", icon: Sparkles },
      { number: "04", title: "InBody", text: "Anthropometric measurements that help guide your training plan.", meta: "Train with better data", image: "/xtreme/consultorio-medicion-corporal.webp", icon: Ruler },
      { number: "05", title: "Tanning room", text: "A dedicated space to achieve and maintain the skin tone you want.", meta: "Wellness · personal care", image: "/xtreme/recepcion-sala-espera.webp", icon: Sun },
      { number: "06", title: "Protein shakes", text: "Practical options to fuel or replenish your energy.", meta: "Recovery · energy", image: "/xtreme/piso-pesas-panoramica.webp", icon: GlassWater },
      { number: "07", title: "Kids play area", text: "A play space that keeps children nearby while you train.", meta: "Play area · no childcare service", image: "/xtreme/area-infantil.webp", icon: Baby },
      { number: "08", title: "Senior fitness", text: "Group classes led by coach Fabio Porras Molina.", meta: "Movement · strength · community", image: "/xtreme/zona-funcional-amplia.webp", href: "/en/seniors", icon: Activity },
    ],
  },
} as const;

export type HomeLocale = keyof typeof HOME_CONTENT;
