"use client";

import { Activity, Clock3, Dumbbell, Ruler } from "lucide-react";
import { GameLabel } from "@/app/components/GameOS";
import type { TrainerOs } from "../hooks/useTrainerOs";

export function TrainerHistory({ os }: { os: TrainerOs }) {
  const member = os.selected!;
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
    <section className="border-[3px] border-white/15 bg-[#0c0c0c] p-4"><GameLabel tone="cyan">Bitácora</GameLabel><h3 className="mt-2 flex items-center gap-2 text-xl font-black uppercase"><Activity className="h-5 w-5 text-cyan-300" /> Ejecución reciente</h3><div className="mt-4 space-y-3">{member.recentWorkouts.map((workout, index) => <article key={workout.id ?? `${workout.completedDate}-${index}`} className="border-[3px] border-white/10 bg-black/25 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-cyan-300">{workout.completedDate || "Sin fecha"}</p><h4 className="mt-1 font-black uppercase">{workout.trainingName || "Entrenamiento"}</h4></div><span className="inline-flex items-center gap-1.5 border-2 border-white/10 px-2 py-1 text-xs font-black text-white/50"><Clock3 className="h-3.5 w-3.5" /> {workout.minutes ?? 0} min</span></div>{workout.exercises?.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{workout.exercises.map((exercise) => <div key={exercise.id} className="border-l-2 border-cyan-300/40 bg-white/[.025] p-2"><p className="text-xs font-black uppercase">{exercise.exerciseName}</p><p className="mt-1 text-[10px] font-bold text-white/40">{exercise.sets}x{exercise.reps} · {exercise.weightKg || 0} kg{exercise.seconds ? ` · ${Math.round(exercise.seconds / 60)} min` : ""}</p>{exercise.notes && <p className="mt-1 text-[10px] font-semibold italic text-white/35">{exercise.notes}</p>}</div>)}</div> : <p className="mt-3 text-xs font-bold text-white/30">Sin detalle de ejercicios.</p>}</article>)}{!member.recentWorkouts.length && <Empty icon={Dumbbell} text="El socio todavía no registra ejecuciones." />}</div></section>
    <section className="border-[3px] border-white/15 bg-[#0c0c0c] p-4"><GameLabel tone="orange">Evolución</GameLabel><h3 className="mt-2 flex items-center gap-2 text-xl font-black uppercase"><Ruler className="h-5 w-5 text-orange-300" /> Mediciones</h3>{member.latestMetrics.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[360px] text-left"><thead><tr className="border-b-[3px] border-white/15 text-[9px] font-black uppercase tracking-[.14em] text-white/35"><th className="py-2">Fecha</th><th>Peso</th><th>Cintura</th></tr></thead><tbody>{member.latestMetrics.map((metric, index) => <tr key={`${metric.date}-${index}`} className="border-b border-white/10"><td className="py-3 text-sm font-bold text-white/50">{metric.date}</td><td className="font-black">{metric.weightKg || "—"} kg</td><td className="font-black">{metric.waistCm || "—"} cm</td></tr>)}</tbody></table></div> : <Empty icon={Ruler} text="Todavía no hay mediciones para comparar." />}</section>
  </div>;
}

function Empty({ icon: Icon, text }: { icon: typeof Dumbbell; text: string }) { return <div className="mt-4 border-[3px] border-dashed border-white/15 p-8 text-center"><Icon className="mx-auto h-8 w-8 text-white/25" /><p className="mt-3 text-sm font-bold text-white/35">{text}</p></div>; }

