import type { GuideWorkout, MachineGuide } from "../domain/training";

/** Extrae el ID de un video de YouTube (watch, youtu.be, shorts, embed). */
export function youtubeVideoId(url: string | undefined): string | null {
  if (!url) return null;
  try {
    const u = new URL(url);
    if (u.hostname.includes("youtu.be")) {
      const id = u.pathname.split("/").filter(Boolean)[0];
      return id || null;
    }
    if (u.hostname.includes("youtube.com")) {
      const v = u.searchParams.get("v");
      if (v) return v;
      const parts = u.pathname.split("/").filter(Boolean);
      if (parts[0] === "embed" || parts[0] === "shorts" || parts[0] === "live") {
        return parts[1] || null;
      }
    }
  } catch {
    return null;
  }
  return null;
}

export function youtubeThumb(url: string | undefined, quality: "hq" | "mq" | "sd" = "hq"): string | null {
  const id = youtubeVideoId(url);
  if (!id) return null;
  return `https://img.youtube.com/vi/${id}/${quality}default.jpg`;
}

/**
 * Guías de máquinas del Member OS.
 *
 * Fuente: auditoría física de activos fijos de Xtreme Gym (131 equipos en 8
 * áreas). Pesas sueltas y discos NO tienen ficha acá — se manejan como
 * inventario aparte (`lib/xtreme/equipment.ts`, admin `/admin/equipo`), no
 * como guía técnica pública. Cada máquina real de esta lista tiene su
 * conteo de unidades en `MACHINE_INVENTORY` (`app/lib/machines.ts`), que
 * alimenta el QR de sala.
 *
 * Fotos: piso real de Xtreme Gym (`/public/xtreme/*`), reusadas entre
 * fichas hasta tener foto propia por máquina. Videos: la mayoría de fichas
 * nuevas no tiene `videoUrl` todavía — se agrega cuando llegue el video
 * propio de cada máquina (archivo en `/public/xtreme/maquinas/*.mp4`).
 */
export const MACHINE_GUIDE: MachineGuide[] = [
  // ── Piernas ──────────────────────────────────────────────────────────
  {
    id: "leg-press",
    name: "Prensa de pierna",
    zone: "Pierna",
    level: "Base",
    muscles: ["Cuadriceps", "Gluteo", "Femoral"],
    setup:
      "Espalda completa apoyada, pies al ancho de hombros y rodillas alineadas con los pies.",
    tips: [
      "Bajá controlado sin despegar la cadera",
      "Empujá con todo el pie",
      "No bloqueés las rodillas arriba",
    ],
    mistakes: [
      "Rodillas hacia adentro",
      "Rango corto sin control",
      "Levantar la cadera del asiento",
    ],
    starter: "3 series de 10 a 12 reps con peso que puedas controlar.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    images: [
      "/xtreme/maquinas-fuerza-xtreme.webp",
      "/xtreme/maquinas-xtreme-amarillas.webp",
      "/xtreme/piso-maquinas-panoramica.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=oujca3_Shgw",
    videoLabel: "Técnica de prensa",
    summary: "Fuerza de pierna completa con la espalda apoyada y sin cargar la zona lumbar.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "leg-extension",
    name: "Extensión de cuádriceps",
    zone: "Pierna",
    level: "Base",
    muscles: ["Cuadriceps"],
    setup:
      "Ajustá el respaldo para que la rodilla quede alineada con el eje y el rodillo sobre el tobillo.",
    tips: [
      "Subí con control hasta casi bloquear sin rebotar",
      "Bajá en 2-3 segundos",
      "Mantené cadera pegada al asiento",
    ],
    mistakes: ["Peso excesivo y balanceo", "Rodillas hacia afuera o adentro", "Rango incompleto"],
    starter: "3 series de 12 a 15 reps, ideal al final de pierna.",
    accent: "from-amber-300 to-yellow-500",
    image: "/xtreme/maquinas-xtreme-amarillas.webp",
    images: [
      "/xtreme/maquinas-xtreme-amarillas.webp",
      "/xtreme/maquinas-fuerza-xtreme.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
    videoLabel: "Extensión de pierna",
    summary: "Aísla el cuádriceps al final del día de pierna con tempo lento y control.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "leg-curl",
    name: "Curl femoral sentado",
    zone: "Pierna",
    level: "Base",
    muscles: ["Femoral", "Pantorrilla", "Gluteo estabilizador"],
    setup: "Alineá la rodilla con el eje de la máquina y el rodillo sobre la parte baja de la pierna.",
    tips: ["Contraé atrás sin arquear la espalda", "No dejes caer el peso", "Usá rango completo"],
    mistakes: ["Levantar la cadera", "Mover muy rapido", "Peso excesivo"],
    starter: "3 series de 12 reps, perfecto para cerrar pierna.",
    accent: "from-lime-300 to-emerald-500",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    images: [
      "/xtreme/maquinas-fuerza-xtreme.webp",
      "/xtreme/piso-maquinas-panoramica.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
    videoLabel: "Curl femoral",
    summary: "Trabaja el femoral y cierra la pierna sin arquear la espalda baja.",
    location: "Planta baja - cerca de los sanitarios",
    kind: "maquina",
  },
  {
    id: "hip-abductor",
    name: "Abductor de cadera",
    zone: "Pierna",
    level: "Base",
    muscles: ["Gluteo medio", "Gluteo menor", "Estabilizadores de cadera"],
    setup:
      "Espalda apoyada, almohadillas en la parte externa de los muslos y rango que no te quite la pelvis del asiento.",
    tips: [
      "Abrí con control apretando glúteo",
      "No rebotés al final del rango",
      "Respirá: exhalá al abrir",
    ],
    mistakes: ["Empujar con los pies en vez de la cadera", "Arquear la espalda baja", "Rango forzado"],
    starter: "3 series de 12 a 15 reps con tempo lento.",
    accent: "from-yellow-200 to-lime-400",
    image: "/xtreme/maquinas-xtreme-amarillas.webp",
    images: [
      "/xtreme/maquinas-xtreme-amarillas.webp",
      "/xtreme/zona-entrenamiento-vip.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=7pbZA7ncuq8",
    videoLabel: "Abductor de cadera",
    summary: "Activa glúteo medio y estabilizadores de cadera con apertura controlada.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "glute-hip-extension",
    name: "Glúteo / extensión de cadera",
    zone: "Pierna",
    level: "Base",
    muscles: ["Gluteo", "Femoral"],
    setup: "Apoyá la rodilla de base sobre la plataforma y enganchá el tobillo contrario en el pad.",
    tips: ["Empujá con el talón, no con la punta", "Apretá glúteo arriba 1 segundo", "Controlá el regreso"],
    mistakes: ["Arquear la espalda para ganar rango", "Usar impulso", "Cadera desalineada"],
    starter: "3 series de 12 a 15 reps por pierna.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Extensión de cadera aislada para activar y fortalecer el glúteo.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "hip-abductor-aductor-dual",
    name: "Abductor / Aductor combinado",
    zone: "Pierna",
    level: "Base",
    muscles: ["Gluteo medio", "Aductores", "Estabilizadores de cadera"],
    setup: "Un solo equipo con dos estaciones: una para abrir (abductor) y otra para cerrar (aductor) las piernas.",
    tips: ["Ajustá el rango antes de cargar peso", "Movimiento controlado en ambas direcciones", "No fuerces el rango máximo"],
    mistakes: ["Rebotar al cerrar o abrir", "Cargar más de lo que controlás", "Ignorar el ajuste de asiento"],
    starter: "3 series de 12 reps en cada estación.",
    accent: "from-yellow-200 to-lime-400",
    image: "/xtreme/maquinas-xtreme-amarillas.webp",
    summary: "Dos estaciones en un equipo: abductor y aductor de cadera.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "pendulum-squat",
    name: "Sentadilla péndulo",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Cuadriceps", "Gluteo"],
    setup: "Hombros bajo las almohadillas, pies adelante del eje de la máquina, espalda apoyada en el respaldo móvil.",
    tips: ["Bajá siguiendo el arco de la máquina", "Empujá con todo el pie", "Rango completo sin dolor de rodilla"],
    mistakes: ["Rodillas muy adelantadas", "Perder el apoyo de espalda", "Rango parcial por miedo al peso"],
    starter: "3 series de 8 a 10 reps, empezando liviano para sentir el arco.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Sentadilla guiada en arco: cuida rodilla y espalda baja mejor que la sentadilla libre.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "leg-press-incline",
    name: "Prensa inclinada",
    zone: "Pierna",
    level: "Base",
    muscles: ["Cuadriceps", "Gluteo", "Femoral"],
    setup: "Espalda completa apoyada en el respaldo inclinado, pies al ancho de hombros sobre la plataforma.",
    tips: ["Bajá controlado sin despegar la cadera", "Empujá con todo el pie", "No bloqueés las rodillas arriba"],
    mistakes: ["Rodillas hacia adentro", "Rango corto sin control", "Levantar la cadera del asiento"],
    starter: "3 series de 10 a 12 reps con peso que puedas controlar.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Variante inclinada de la prensa de pierna, mismo patrón de empuje.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "horizontal-leg-press",
    name: "Prensa horizontal",
    zone: "Pierna",
    level: "Base",
    muscles: ["Cuadriceps", "Gluteo", "Femoral"],
    setup: "Acostado con la espalda apoyada, empujás la plataforma en línea recta frente a vos.",
    tips: ["Empujá con todo el pie, no con la punta", "Bajá controlado", "No bloqueés las rodillas arriba"],
    mistakes: ["Rango corto sin control", "Rodillas hacia adentro", "Soltar el peso de golpe"],
    starter: "3 series de 10 a 12 reps con peso controlable.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Prensa horizontal: mismo patrón de empuje que la prensa inclinada, en plano recto.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "lying-squat",
    name: "Sentadilla acostado",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Cuadriceps", "Gluteo"],
    setup: "Acostado boca arriba, espalda y cadera apoyadas, pies sobre la plataforma frontal.",
    tips: ["Rango completo sin despegar la cadera", "Exhalá al empujar", "Controlá la bajada"],
    mistakes: ["Despegar la cadera del asiento", "Bloquear rodillas de golpe", "Rango parcial"],
    starter: "3 series de 10 a 12 reps.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Sentadilla guiada en posición acostada, protege la zona lumbar.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "leg-curl-extension-dual",
    name: "Leg Curl + Leg Extension combinado",
    zone: "Pierna",
    level: "Base",
    muscles: ["Femoral", "Cuadriceps"],
    setup: "Un equipo con dos estaciones: curl femoral de un lado, extensión de cuádriceps del otro.",
    tips: ["Ajustá el rodillo a la altura del tobillo antes de empezar", "Movimiento controlado en las dos estaciones", "No rebotes al final del rango"],
    mistakes: ["Peso excesivo con balanceo", "Rango incompleto", "Saltar el ajuste de asiento"],
    starter: "3 series de 12 reps en cada estación.",
    accent: "from-lime-300 to-emerald-500",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Curl femoral y extensión de cuádriceps en un mismo equipo de dos estaciones.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "lying-leg-curl",
    name: "Leg Curl acostado (camilla)",
    zone: "Pierna",
    level: "Base",
    muscles: ["Femoral", "Gluteo estabilizador"],
    setup: "Acostado boca abajo sobre la camilla, rodillo justo sobre el tendón de Aquiles.",
    tips: ["Contraé atrás sin levantar la cadera", "Bajá en 2-3 segundos", "Rango completo sin rebote"],
    mistakes: ["Levantar la cadera de la camilla", "Mover muy rápido", "Peso excesivo"],
    starter: "3 series de 12 reps.",
    accent: "from-lime-300 to-emerald-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Curl femoral acostado, aísla el femoral con la cadera fija en la camilla.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "smith-machine",
    name: "Máquina Smith",
    zone: "Full body",
    level: "Todos",
    muscles: ["Cuerpo completo", "Cuadriceps", "Pecho", "Hombro"],
    setup: "Barra guiada sobre rieles verticales con seguros de trabas cada pocos centímetros.",
    tips: ["Trabá los seguros antes de soltar la barra", "Alineá el ejercicio con el riel", "Empezá liviano para sentir la trayectoria fija"],
    mistakes: ["Sentadilla con los pies muy atrás del riel", "Confiar en la trayectoria fija para ir sin calentar", "No trabar los seguros al terminar"],
    starter: "Usala para sentadilla, press de banca o press militar guiado.",
    accent: "from-fuchsia-400 to-purple-500",
    image: "/xtreme/piso-pesas-panoramica.webp",
    summary: "Riel guiado para sentadilla, press y más — trayectoria fija y segura para practicar patrones.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "sentadilla-potro",
    name: "Sentadilla potro",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Cuadriceps", "Gluteo"],
    setup: "Apoyate en el potro/pecho del equipo y ejecutá el patrón de sentadilla guiada que indica la máquina.",
    tips: ["Espalda neutral durante todo el recorrido", "Bajá con control", "Empujá con todo el pie"],
    mistakes: ["Redondear la espalda", "Rango forzado", "Soltar el peso arriba"],
    starter: "3 series de 10 reps con peso moderado.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Sentadilla guiada tipo potro, apoyo frontal para proteger la espalda baja.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "calf-press-horizontal",
    name: "Pantorrilla horizontal",
    zone: "Pierna",
    level: "Base",
    muscles: ["Pantorrilla"],
    setup: "Pies apoyados en la punta de la plataforma, empujás extendiendo el tobillo.",
    tips: ["Rango completo: estiramiento abajo, contracción arriba", "Pausa 1 segundo arriba", "No rebotes"],
    mistakes: ["Rango corto", "Rebotar para mover más peso", "Doblar rodilla para ayudar"],
    starter: "3 series de 15 a 20 reps.",
    accent: "from-amber-300 to-yellow-500",
    image: "/xtreme/maquinas-xtreme-amarillas.webp",
    summary: "Aísla la pantorrilla con extensión de tobillo contra la plataforma.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },
  {
    id: "sissy-squat",
    name: "Sissy Squats",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Cuadriceps"],
    setup: "Asegurá los tobillos en el soporte y bajá el torso hacia atrás manteniendo las caderas extendidas.",
    tips: ["Bajá con control, sin caer", "Mantené la cadera extendida durante todo el movimiento", "Empezá con rango parcial si es tu primera vez"],
    mistakes: ["Flexionar la cadera en vez de solo la rodilla", "Bajar sin control", "Rango excesivo antes de tener movilidad"],
    starter: "3 series de 8 a 10 reps, rango parcial al inicio.",
    accent: "from-amber-300 to-yellow-500",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Aislamiento intenso de cuádriceps con la cadera fija en extensión.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Cuadriceps", "Gluteo"],
    setup: "Espalda y hombros apoyados en el respaldo inclinado, pies al ancho de hombros sobre la plataforma.",
    tips: ["Bajá hasta donde la espalda baja se mantenga pegada", "Empujá con todo el pie", "Rodillas alineadas con los pies"],
    mistakes: ["Despegar la espalda baja del respaldo", "Rodillas hacia adentro", "Bloquear de golpe arriba"],
    starter: "3 series de 8 a 10 reps con peso controlable.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Sentadilla guiada en riel inclinado, gran estímulo de cuádriceps con espalda protegida.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "sentadilla-perfecta",
    name: "Sentadilla Perfecta",
    zone: "Pierna",
    level: "Base",
    muscles: ["Cuadriceps", "Gluteo"],
    setup: "Seguí el patrón guiado de la máquina, manteniendo espalda neutral y peso en todo el pie.",
    tips: ["Bajá con control siguiendo el recorrido de la máquina", "Empujá con todo el pie", "Mirada al frente"],
    mistakes: ["Perder la postura a mitad de rango", "Rango parcial", "Soltar el agarre antes de terminar"],
    starter: "3 series de 10 a 12 reps.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Sentadilla guiada de bajo impacto, ideal para aprender el patrón con seguridad.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "tubo-pesas-pendiente",
    name: "Máquina de tubo con pesas (por identificar)",
    zone: "Pierna",
    level: "Todos",
    muscles: ["Por confirmar"],
    setup: "Ficha en construcción — modelo pendiente de identificar en el piso.",
    tips: ["Pedí a un entrenador que te muestre el uso mientras completamos la ficha"],
    mistakes: ["No usar sin haber visto la técnica una vez"],
    starter: "Consultá con un entrenador de planta antes de usarla.",
    accent: "from-slate-300 to-zinc-400",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Equipo pequeño con tubo y pesas en los extremos — guía completa en camino.",
    location: "Planta baja - zona techada (cerca de comidas)",
    kind: "maquina",
  },
  {
    id: "multiestacion-pie-pendiente",
    name: "Multi-estación de pie (por identificar)",
    zone: "Full body",
    level: "Todos",
    muscles: ["Por confirmar"],
    setup: "Ficha en construcción — modelo pendiente de identificar en el piso.",
    tips: ["Dejala descargada al terminar de usarla", "Pedí a un entrenador que te muestre el uso mientras completamos la ficha"],
    mistakes: ["No usar sin haber visto la técnica una vez"],
    starter: "Consultá con un entrenador de planta antes de usarla.",
    accent: "from-slate-300 to-zinc-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Multi-estación de pie — guía completa en camino.",
    location: "Planta baja - frente a bronceado / venta de batidos",
    kind: "maquina",
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust (rack con plataforma)",
    zone: "Pierna",
    level: "Intermedio",
    muscles: ["Gluteo", "Femoral"],
    setup: "Espalda alta apoyada en el respaldo acolchado, barra o plataforma sobre la cadera, pies firmes en el piso.",
    tips: ["Empujá con los talones y apretá glúteo arriba", "No hiperextiendas la espalda baja al subir", "Barbilla metida durante todo el movimiento"],
    mistakes: ["Arquear la zona lumbar para ganar altura", "Rango incompleto", "Pies muy adelante o muy atrás de la rodilla"],
    starter: "3 series de 10 a 12 reps con peso controlable.",
    accent: "from-yellow-300 to-orange-400",
    image: "/xtreme/zona-entrenamiento-vip.webp",
    summary: "El mejor constructor de glúteo: extensión de cadera con la espalda alta apoyada.",
    location: "Planta baja - zona techada (frente a juegos/comida/baños)",
    kind: "maquina",
  },

  // ── Cardio ───────────────────────────────────────────────────────────
  {
    id: "treadmill",
    name: "Cinta de correr",
    zone: "Cardio",
    level: "Todos",
    muscles: ["Sistema cardiovascular", "Piernas"],
    setup: "Amarrá bien los zapatos, colocá el clip de seguridad y arrancá caminando antes de subir la velocidad.",
    tips: [
      "Podés hacer intervalos (ej. 30s fuerte / 90s suave)",
      "Postura erguida, mirada al frente, no te colgués del manubrio",
      "Bajá la velocidad antes de bajarte",
    ],
    mistakes: ["Subir la velocidad de golpe sin calentar", "Correr sin el clip de seguridad puesto", "Mirar el teléfono en vez del frente"],
    starter: "15-25 min: 5 calentamiento + 10-15 trote/intervalos + 5 vuelta a la calma.",
    accent: "from-cyan-400 to-teal-500",
    image: "/xtreme/zona-cardio.webp",
    images: ["/xtreme/zona-cardio.webp", "/xtreme/zona-funcional-clases.webp"],
    summary: "Caminar, trotar o correr con control de velocidad e inclinación.",
    location: "Planta baja - área de máquinas de correr",
    kind: "maquina",
  },
  {
    id: "stair-stepper",
    name: "Caminadora tipo escalera (stepper)",
    zone: "Cardio",
    level: "Todos",
    muscles: ["Sistema cardiovascular", "Gluteo", "Piernas"],
    setup: "Subite con los pies sobre los pedales, agarrate liviano de los laterales y mantené el torso erguido.",
    tips: ["Pasos cortos y constantes, no zancadas largas", "Apoyate poco en los brazos, dejá que trabajen las piernas", "Empezá con resistencia baja"],
    mistakes: ["Apoyar todo el peso en los brazos", "Bloquear las rodillas en cada paso", "Subir la resistencia antes de dominar el ritmo"],
    starter: "10-15 min a ritmo sostenido, subiendo resistencia cada pocos minutos.",
    accent: "from-cyan-400 to-teal-500",
    image: "/xtreme/zona-cardio.webp",
    summary: "Cardio de bajo impacto que suma trabajo de glúteo y pierna.",
    location: "Planta baja - área de máquinas de correr",
    kind: "maquina",
  },
  {
    id: "stair-climber",
    name: "Máquina de gradas (stair climber)",
    zone: "Cardio",
    level: "Intermedio",
    muscles: ["Sistema cardiovascular", "Gluteo", "Cuadriceps"],
    setup: "Subite despacio hasta agarrar el ritmo de los escalones, mantené el torso erguido sin apoyarte de más.",
    tips: ["Pisá completo en cada escalón", "Torso erguido, core activo", "Empezá a ritmo bajo hasta agarrar confianza"],
    mistakes: ["Apoyarse mucho en los pasamanos", "Pisar solo con la punta del pie", "Subir el ritmo antes de tener equilibrio"],
    starter: "10-15 min a ritmo constante.",
    accent: "from-cyan-400 to-teal-500",
    image: "/xtreme/zona-cardio.webp",
    summary: "Simula subir gradas sin parar — cardio intenso con foco en gluteo y pierna.",
    location: "Planta baja - área de máquinas de correr",
    kind: "maquina",
  },

  // ── Espalda / poleas ─────────────────────────────────────────────────
  {
    id: "lat-pulldown",
    name: "Jalon al pecho",
    zone: "Espalda",
    level: "Base",
    muscles: ["Dorsal", "Biceps", "Espalda media"],
    setup: "Asegurá las piernas, pecho alto y agarre un poco más ancho que hombros.",
    tips: [
      "Jalá hacia la parte alta del pecho",
      "Pensá en bajar los codos",
      "Controlá el regreso sin soltar tensión",
    ],
    mistakes: ["Jalar detras de la nuca", "Usar impulso del torso", "Encoger los hombros"],
    starter: "3 series de 10 reps con pausa corta abajo.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    images: [
      "/xtreme/piso-maquinas-panoramica.webp",
      "/xtreme/maquinas-y-entrenador-xtreme.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    videoLabel: "Jalón al pecho",
    summary: "Construye espalda ancha con jalón vertical hacia la parte alta del pecho.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "seated-row",
    name: "Remo sentado",
    zone: "Espalda",
    level: "Intermedio",
    muscles: ["Espalda media", "Dorsal", "Biceps"],
    setup: "Pecho firme, columna neutral y agarre con brazos estirados sin redondear la espalda.",
    tips: ["Llevá los codos atrás", "Apretá espalda un segundo", "Volvé lento al inicio"],
    mistakes: ["Balancear el cuerpo", "Redondear la espalda", "Jalar solo con brazos"],
    starter: "3 series de 10 a 12 reps con tempo controlado.",
    accent: "from-cyan-300 to-blue-500",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    images: [
      "/xtreme/maquinas-fuerza-xtreme.webp",
      "/xtreme/piso-maquinas-panoramica.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
    videoLabel: "Remo en polea sentado",
    summary: "Grosor de espalda media con tirón horizontal y columna neutral.",
    location: "Planta baja - área de pesas",
    kind: "maquina",
  },
  {
    id: "remo-hammer-strength",
    name: "Remo cerrado (Hammer Strength)",
    zone: "Espalda",
    level: "Intermedio",
    muscles: ["Espalda media", "Dorsal", "Biceps"],
    setup: "Pecho apoyado en el respaldo, agarre cerrado, codos pegados al cuerpo al jalar.",
    tips: ["Jalá con los codos, no con las manos", "Apretá omóplatos al final", "Volvé con control"],
    mistakes: ["Impulsar con el torso", "Rango incompleto", "Soltar el peso de golpe"],
    starter: "3 series de 10 reps.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Remo con placas y pecho apoyado, agarre cerrado para grosor de espalda media.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "remo-hammer",
    name: "Remo Hammer",
    zone: "Espalda",
    level: "Intermedio",
    muscles: ["Espalda media", "Dorsal", "Biceps"],
    setup: "Pecho apoyado en el respaldo, agarre a definir según el ejercicio que busques.",
    tips: ["Jalá con los codos", "Controlá el regreso", "No uses impulso del torso"],
    mistakes: ["Rango incompleto", "Soltar el peso de golpe", "Encoger los hombros al jalar"],
    starter: "3 series de 10 reps.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Remo con pecho apoyado, variante Hammer Strength.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "remo-t",
    name: "Remo T",
    zone: "Espalda",
    level: "Intermedio",
    muscles: ["Espalda media", "Dorsal", "Biceps"],
    setup: "Pecho apoyado en el soporte, agarrá la barra en T y jalá manteniendo la columna neutral.",
    tips: ["Codos cerca del cuerpo al jalar", "Apretá espalda arriba", "Bajá con control total"],
    mistakes: ["Redondear la espalda", "Usar solo brazos", "Rango parcial"],
    starter: "3 series de 10 reps.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Remo en barra T con pecho apoyado para aislar la espalda media.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "back-extension",
    name: "Back extension",
    zone: "Espalda",
    level: "Base",
    muscles: ["Lumbar", "Gluteo", "Femoral"],
    setup: "Cadera apoyada en el borde del pad, tobillos asegurados, torso colgando en línea con las piernas.",
    tips: ["Subí hasta que el cuerpo quede recto, sin hiperextender", "Apretá glúteo arriba", "Bajá con control"],
    mistakes: ["Hiperextender la zona lumbar arriba", "Rebotar abajo", "Subir de golpe con impulso"],
    starter: "3 series de 12 a 15 reps.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Fortalece la zona lumbar y el glúteo con extensión de cadera controlada.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "dominada-asistida",
    name: "Dominada asistida",
    zone: "Espalda",
    level: "Base",
    muscles: ["Dorsal", "Biceps", "Espalda media"],
    setup: "Rodillas o pies sobre la plataforma asistida, agarre ancho en las barras superiores.",
    tips: ["Más peso en el contador = más ayuda; bajalo con el tiempo", "Jalá con los codos hacia abajo", "Controlá la bajada"],
    mistakes: ["Usar demasiada asistencia todo el tiempo", "Rango incompleto", "Balancearse para ganar impulso"],
    starter: "3 series de 8 a 10 reps con la asistencia que te permita completar el rango.",
    accent: "from-sky-300 to-cyan-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Practicá la dominada con asistencia progresiva mientras ganás fuerza.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "rear-delt-fly",
    name: "Aperturas posteriores (Pec Deck Rear Delt)",
    zone: "Hombro",
    level: "Intermedio",
    muscles: ["Hombro posterior", "Espalda media"],
    setup: "Pecho apoyado en el respaldo, mirando hacia la máquina, agarraderas a la altura del hombro.",
    tips: ["Abrí los brazos hacia atrás sin usar impulso", "Apretá omóplatos al final", "Controlá el regreso"],
    mistakes: ["Usar demasiado peso y perder rango", "Encoger los hombros", "Impulsar con el torso"],
    starter: "3 series de 12 a 15 reps.",
    accent: "from-violet-400 to-purple-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Aísla el deltoide posterior — clave para hombros equilibrados y postura sana.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },

  // ── Pecho / hombro ───────────────────────────────────────────────────
  {
    id: "chest-press",
    name: "Press de pecho",
    zone: "Pecho",
    level: "Base",
    muscles: ["Pecho", "Triceps", "Hombro frontal"],
    setup: "Ajustá el asiento para que las agarraderas queden a media altura del pecho.",
    tips: [
      "Mantené escápulas atrás",
      "Empujá sin despegar la espalda",
      "Regresá lento hasta sentir estiramiento",
    ],
    mistakes: ["Subir los hombros", "Rebotar el peso", "Abrir demasiado los codos"],
    starter: "3 series de 8 a 12 reps, descansando 60 a 90 segundos.",
    accent: "from-red-400 to-rose-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    images: [
      "/xtreme/maquinas-y-entrenador-xtreme.webp",
      "/xtreme/piso-maquinas-panoramica.webp",
      "/xtreme/maquinas-fuerza-xtreme.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=xUm0BiZCWlQ",
    videoLabel: "Press de pecho en máquina",
    summary: "Empuje horizontal guiado para pecho, con trayectoria fija y segura.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "incline-chest-press",
    name: "Press de pecho inclinado",
    zone: "Pecho",
    level: "Base",
    muscles: ["Pecho superior", "Hombro frontal", "Triceps"],
    setup: "Ajustá el asiento para que las agarraderas queden a la altura de la clavícula.",
    tips: ["Empujá hacia arriba y al frente, sin arquear de más", "Escápulas atrás y abajo", "Bajá con control"],
    mistakes: ["Arquear demasiado la espalda baja", "Rebotar el peso", "Rango incompleto"],
    starter: "3 series de 8 a 12 reps.",
    accent: "from-red-400 to-rose-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Press inclinado guiado, prioriza la parte superior del pecho.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "pec-deck",
    name: "Pec deck / mariposa",
    zone: "Pecho",
    level: "Intermedio",
    muscles: ["Pecho", "Hombro frontal"],
    setup:
      "Asiento a altura de codos con los brazos, antebrazos en los pads y pecho alto sin hundir el pecho.",
    tips: [
      "Cerrá como si abrazaras un barril",
      "Pausa de 1 segundo al centro",
      "Abrí controlado sin soltar del todo la tensión",
    ],
    mistakes: ["Empujar con hombros hacia adelante", "Rebote en el centro", "Peso que no controlás"],
    starter: "3 series de 10 a 12 reps, buen complemento del press.",
    accent: "from-rose-400 to-pink-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    images: [
      "/xtreme/piso-maquinas-panoramica.webp",
      "/xtreme/maquinas-y-entrenador-xtreme.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=gF1JRFNeOXw",
    videoLabel: "Pec deck / fly máquina",
    summary: "Aísla el pecho con un recorrido de apertura y cierre tipo abrazo.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "shoulder-press",
    name: "Press de hombro",
    zone: "Hombro",
    level: "Base",
    muscles: ["Hombro", "Triceps", "Trapecio superior"],
    setup:
      "Asiento con respaldo, agarres a la altura de las orejas y pies firmes en el piso.",
    tips: [
      "Empujá hacia arriba sin arquear la lumbar",
      "No bloqueés los codos de golpe",
      "Bajá hasta ~90° de codo",
    ],
    mistakes: ["Empujar con el pecho hacia adelante", "Peso que te saca del asiento", "Encoger cuello"],
    starter: "3 series de 8 a 12 reps con control total.",
    accent: "from-violet-400 to-purple-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    images: [
      "/xtreme/maquinas-y-entrenador-xtreme.webp",
      "/xtreme/maquinas-xtreme-amarillas.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=Wqq43dKW1TU",
    videoLabel: "Press de hombro en máquina",
    summary: "Empuje vertical guiado para hombro sin comprometer la zona lumbar.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "overhead-press-machine",
    name: "Overhead press (press militar)",
    zone: "Hombro",
    level: "Intermedio",
    muscles: ["Hombro", "Triceps", "Trapecio superior"],
    setup: "Sentado con espalda firme, agarre a la altura del hombro, codos ligeramente adelante.",
    tips: ["Empujá recto hacia arriba", "No arquear la lumbar para completar el rango", "Bajá con control hasta ~90°"],
    mistakes: ["Arquear la espalda baja", "Encoger el cuello al empujar", "Rango incompleto"],
    starter: "3 series de 8 a 10 reps.",
    accent: "from-violet-400 to-purple-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Press militar guiado para hombro completo.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },

  // ── Core / brazo ─────────────────────────────────────────────────────
  {
    id: "torso-rotation",
    name: "Rotación de tronco",
    zone: "Core",
    level: "Base",
    muscles: ["Oblicuos", "Core"],
    setup: "Sentado con cadera fija, agarrá las manijas y girá el torso hacia cada lado desde el centro.",
    tips: ["Girá desde el core, no solo los brazos", "Rango controlado sin forzar", "Exhalá al girar"],
    mistakes: ["Usar impulso en vez de contracción", "Rango excesivo que fuerza la zona lumbar", "Peso excesivo"],
    starter: "3 series de 12 a 15 reps por lado.",
    accent: "from-teal-300 to-emerald-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Trabaja los oblicuos con rotación controlada de tronco.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "ab-machine",
    name: "Abdominal",
    zone: "Core",
    level: "Base",
    muscles: ["Recto abdominal", "Oblicuos"],
    setup: "Sentado, torso apoyado en el respaldo superior, engancha los pies o piernas según el modelo.",
    tips: ["Flexioná desde el abdomen, no tires del cuello", "Exhalá al contraer", "Rango controlado sin rebote"],
    mistakes: ["Jalar con el cuello", "Usar impulso", "Rango excesivo sin control"],
    starter: "3 series de 15 a 20 reps.",
    accent: "from-teal-300 to-emerald-500",
    image: "/xtreme/piso-maquinas-panoramica.webp",
    summary: "Flexión de tronco guiada para trabajar el recto abdominal.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
  {
    id: "preacher-curl",
    name: "Predicador (curl de bíceps)",
    zone: "Brazo",
    level: "Base",
    muscles: ["Biceps"],
    setup: "Axilas apoyadas en el pad inclinado, agarre a la altura de los hombros.",
    tips: ["Bajá con control hasta casi extender el codo", "No despegues las axilas del pad", "Subí sin balancear el cuerpo"],
    mistakes: ["Despegar los codos del pad", "Rango incompleto", "Usar impulso del torso"],
    starter: "3 series de 10 a 12 reps.",
    accent: "from-orange-400 to-red-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Aísla el bíceps con los codos fijos sobre el pad inclinado.",
    location: "Zona Central - Debajo del reloj",
    kind: "maquina",
  },
  {
    id: "elbow-extension",
    name: "Extensión de codo (tríceps)",
    zone: "Brazo",
    level: "Base",
    muscles: ["Triceps"],
    setup: "Codos fijos junto al torso o sobre el pad, según el modelo, agarre firme en la barra o manija.",
    tips: ["Extendé el codo sin mover el hombro", "Controlá el regreso", "Codos pegados al cuerpo todo el movimiento"],
    mistakes: ["Mover el hombro para ayudar", "Rango incompleto", "Soltar el peso de golpe"],
    starter: "3 series de 12 a 15 reps.",
    accent: "from-orange-400 to-red-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Aísla el tríceps con extensión de codo controlada.",
    location: "Zona Central - Debajo del reloj",
    kind: "maquina",
  },
  {
    id: "dip-machine",
    name: "Fondos (dips) asistidos",
    zone: "Brazo",
    level: "Intermedio",
    muscles: ["Triceps", "Pecho", "Hombro frontal"],
    setup: "Agarre en las barras paralelas, torso ligeramente inclinado adelante, ajustá la asistencia si el equipo lo permite.",
    tips: ["Bajá hasta 90° de codo, no más", "Codos cerca del cuerpo para enfocar tríceps", "Empujá con control, sin rebote abajo"],
    mistakes: ["Bajar más de 90° sin movilidad", "Encoger los hombros", "Usar impulso"],
    starter: "3 series de 8 a 10 reps con la asistencia necesaria.",
    accent: "from-orange-400 to-red-400",
    image: "/xtreme/maquinas-fuerza-xtreme.webp",
    summary: "Fondos guiados para tríceps y pecho bajo, con asistencia progresiva.",
    location: "Zona Central - Debajo del reloj",
    kind: "maquina",
  },

  // ── Full body / poleas ───────────────────────────────────────────────
  {
    id: "cable-station",
    name: "Polea ajustable",
    zone: "Full body",
    level: "Versatil",
    muscles: ["Core", "Hombros", "Brazos", "Gluteo"],
    setup: "Ajustá la polea según el ejercicio y mantené una postura estable antes de iniciar.",
    tips: [
      "Empezá liviano para sentir trayectoria",
      "Mantené abdomen firme",
      "Evitá tirones bruscos",
    ],
    mistakes: ["Perder postura", "Cambiar angulo a mitad de repeticion", "Usar impulso"],
    starter: "2 a 4 series de 12 reps según el ejercicio elegido.",
    accent: "from-fuchsia-400 to-purple-500",
    image: "/xtreme/zona-funcional-turf.webp",
    images: [
      "/xtreme/zona-funcional-turf.webp",
      "/xtreme/zona-funcional-amplia.webp",
      "/xtreme/zona-mancuernas.webp",
    ],
    videoUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk",
    videoLabel: "Face pulls y trabajo en polea",
    summary: "Estación versátil: ajustás la altura de la polea y trabajás casi cualquier grupo.",
    location: "Poleas adicionales - frente a caminadoras / frente al VIP",
    kind: "maquina",
  },
  {
    id: "polea-crossover",
    name: "Polea crossover (4 estaciones)",
    zone: "Full body",
    level: "Intermedio",
    muscles: ["Pecho", "Espalda", "Hombros", "Core"],
    setup: "Cuatro puntos de anclaje (poleas altas, bajas y banquita con apoyo de rodillas) para combinar ejercicios.",
    tips: ["Elegí la altura de polea según el ejercicio", "Postura estable antes de tirar", "Movimientos controlados, sin tirones"],
    mistakes: ["Cambiar de altura a mitad de serie", "Perder la postura del core", "Usar impulso del cuerpo"],
    starter: "2 a 4 series de 12 reps según el ejercicio elegido.",
    accent: "from-fuchsia-400 to-purple-500",
    image: "/xtreme/zona-funcional-amplia.webp",
    summary: "Estación de crossover con 4 puntos de polea para combinar ejercicios de pecho, espalda y core.",
    location: "Zona Central - Debajo del reloj",
    kind: "maquina",
  },
  {
    id: "bicicleta-estatica",
    name: "Bicicleta estática",
    zone: "Cardio",
    level: "Todos",
    muscles: ["Sistema cardiovascular", "Cuadriceps", "Femoral"],
    setup: "Ajustá el sillín a la altura de la cadera y empezá pedaleando suave 3-5 min para calentar.",
    tips: ["Postura erguida, core activo", "Podés hacer intervalos de resistencia", "Hidratate durante la sesión"],
    mistakes: ["Sillín muy bajo o muy alto", "Empezar a tope sin calentar", "Encorvarte sobre el manubrio"],
    starter: "15-25 min: calentamiento + intervalos + vuelta a la calma.",
    accent: "from-cyan-400 to-teal-500",
    image: "/xtreme/zona-cardio.webp",
    summary: "Cardio de bajo impacto, ideal para calentar o cerrar la sesión.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "multiestacion-recepcion",
    name: "Máquina multi-estación",
    zone: "Full body",
    level: "Todos",
    muscles: ["Cuerpo completo"],
    setup: "Asiento ajustable, soporte de espalda y agarraderas múltiples — pedí a un entrenador que te muestre las variantes disponibles.",
    tips: ["Ajustá el asiento antes de empezar", "Empezá liviano para probar cada estación", "Consultá con un entrenador el uso exacto"],
    mistakes: ["Usar sin ajustar el asiento", "Forzar una postura incómoda"],
    starter: "Consultá con un entrenador de planta para armar tu circuito.",
    accent: "from-fuchsia-400 to-purple-500",
    image: "/xtreme/maquinas-y-entrenador-xtreme.webp",
    summary: "Estación múltiple con varios agarres y ajustes — guía detallada en camino.",
    location: "Recepción - Izquierda - Piso",
    kind: "maquina",
  },
  {
    id: "banca-inclinada-pendiente",
    name: "Banca inclinada con postes (por definir)",
    zone: "Pecho",
    level: "Todos",
    muscles: ["Pecho", "Hombro frontal"],
    setup: "Ficha en construcción — uso exacto pendiente de confirmar.",
    tips: ["Pedí a un entrenador que te muestre el uso mientras completamos la ficha"],
    mistakes: ["No usar sin haber visto la técnica una vez"],
    starter: "Consultá con un entrenador de planta antes de usarla.",
    accent: "from-red-400 to-rose-500",
    image: "/xtreme/piso-pesas-panoramica.webp",
    summary: "Banca inclinada con postes laterales para barra — guía completa en camino.",
    location: "Recepción - Derecha - Piso",
    kind: "maquina",
  },
];

export const GUIDE_WORKOUTS: GuideWorkout[] = [
  {
    goal: "Primer dia",
    steps: ["Prensa 3x10", "Press pecho 3x10", "Jalon 3x10", "Curl femoral 2x12"],
  },
  {
    goal: "Fuerza base",
    steps: ["Prensa 4x8", "Remo sentado 4x8", "Press pecho 4x8", "Polea core 3x12"],
  },
  {
    goal: "Control tecnico",
    steps: ["Jalon 3x12 lento", "Curl femoral 3x12", "Remo sentado 3x10", "Polea 3x15"],
  },
  {
    goal: "Lower + gluteo",
    steps: ["Prensa 3x12", "Curl femoral 3x12", "Abductor 3x15", "Extensión 2x15"],
  },
  {
    goal: "Tren superior",
    steps: ["Press pecho 3x10", "Jalon 3x10", "Remo 3x10", "Press hombro 3x10"],
  },
];

export function findMachineGuide(machineId: MachineGuide["id"]) {
  return MACHINE_GUIDE.find((machine) => machine.id === machineId) ?? null;
}
